# Generated by Django 6.1.1 on 2026-09-07 09:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
            },
        ),
        migrations.CreateModel(
            name='TechnicianContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('media_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('id_document_url', models.URLField(blank=True, max_length=500)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('training_completed', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(choices=[('trial_active', 'Trial Active'), ('active', 'Active'), ('lapsed', 'Lapsed'), ('suspended', 'Suspended')], default='lapsed', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=-1.9441, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=30.0619, max_digits=9, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='technicians', to='technicians.servicecategory')),
            ],
        ),
    ]
