# Generated by Django 6.1.1 on 2026-09-07 09:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_ref', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount_rwf', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Card')], default='momo', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.CharField(default='plan_monthly_pro', max_length=50)),
                ('status', models.CharField(choices=[('trial_active', 'Trial Active'), ('active', 'Active'), ('lapsed', 'Lapsed'), ('suspended', 'Suspended')], default='trial_active', max_length=20)),
                ('amount_rwf', models.PositiveIntegerField(default=15000)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
